# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\x04\x65\x63ho\"0\n\x0b\x45\x63hoMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"3\n\x0c\x44\x65layedReply\x12#\n\x08response\x18\x01 \x03(\x0b\x32\x11.echo.EchoMessage2\xb6\x01\n\x0b\x45\x63hoService\x12\x37\n\x0c\x43lientStream\x12\x11.echo.EchoMessage\x1a\x12.echo.DelayedReply(\x01\x12\x36\n\x0cServerStream\x12\x11.echo.EchoMessage\x1a\x11.echo.EchoMessage0\x01\x12\x36\n\nBothStream\x12\x11.echo.EchoMessage\x1a\x11.echo.EchoMessage(\x01\x30\x01\x62\x06proto3')



_ECHOMESSAGE = DESCRIPTOR.message_types_by_name['EchoMessage']
_DELAYEDREPLY = DESCRIPTOR.message_types_by_name['DelayedReply']
EchoMessage = _reflection.GeneratedProtocolMessageType('EchoMessage', (_message.Message,), {
  'DESCRIPTOR' : _ECHOMESSAGE,
  '__module__' : 'echo_pb2'
  # @@protoc_insertion_point(class_scope:echo.EchoMessage)
  })
_sym_db.RegisterMessage(EchoMessage)

DelayedReply = _reflection.GeneratedProtocolMessageType('DelayedReply', (_message.Message,), {
  'DESCRIPTOR' : _DELAYEDREPLY,
  '__module__' : 'echo_pb2'
  # @@protoc_insertion_point(class_scope:echo.DelayedReply)
  })
_sym_db.RegisterMessage(DelayedReply)

_ECHOSERVICE = DESCRIPTOR.services_by_name['EchoService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ECHOMESSAGE._serialized_start=20
  _ECHOMESSAGE._serialized_end=68
  _DELAYEDREPLY._serialized_start=70
  _DELAYEDREPLY._serialized_end=121
  _ECHOSERVICE._serialized_start=124
  _ECHOSERVICE._serialized_end=306
# @@protoc_insertion_point(module_scope)
