# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_core.protos.check import check_pb2 as check_dot_check__pb2


class CheckStatusOrderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckStatusOrder = channel.unary_unary(
                '/check.CheckStatusOrderService/CheckStatusOrder',
                request_serializer=check_dot_check__pb2.CheckStatusOrderRequest.SerializeToString,
                response_deserializer=check_dot_check__pb2.CheckStatusOrderResponse.FromString,
                )


class CheckStatusOrderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckStatusOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CheckStatusOrderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckStatusOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatusOrder,
                    request_deserializer=check_dot_check__pb2.CheckStatusOrderRequest.FromString,
                    response_serializer=check_dot_check__pb2.CheckStatusOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'check.CheckStatusOrderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CheckStatusOrderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckStatusOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/check.CheckStatusOrderService/CheckStatusOrder',
            check_dot_check__pb2.CheckStatusOrderRequest.SerializeToString,
            check_dot_check__pb2.CheckStatusOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
