# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: check/check.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63heck/check.proto\x12\x05\x63heck\x1a\x1egoogle/protobuf/wrappers.proto\"\'\n\x17\x43heckStatusOrderRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"W\n\x18\x43heckStatusOrderResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12-\n\tcompleted\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.BoolValue2n\n\x17\x43heckStatusOrderService\x12S\n\x10\x43heckStatusOrder\x12\x1e.check.CheckStatusOrderRequest\x1a\x1f.check.CheckStatusOrderResponseb\x06proto3')



_CHECKSTATUSORDERREQUEST = DESCRIPTOR.message_types_by_name['CheckStatusOrderRequest']
_CHECKSTATUSORDERRESPONSE = DESCRIPTOR.message_types_by_name['CheckStatusOrderResponse']
CheckStatusOrderRequest = _reflection.GeneratedProtocolMessageType('CheckStatusOrderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKSTATUSORDERREQUEST,
  '__module__' : 'check.check_pb2'
  # @@protoc_insertion_point(class_scope:check.CheckStatusOrderRequest)
  })
_sym_db.RegisterMessage(CheckStatusOrderRequest)

CheckStatusOrderResponse = _reflection.GeneratedProtocolMessageType('CheckStatusOrderResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKSTATUSORDERRESPONSE,
  '__module__' : 'check.check_pb2'
  # @@protoc_insertion_point(class_scope:check.CheckStatusOrderResponse)
  })
_sym_db.RegisterMessage(CheckStatusOrderResponse)

_CHECKSTATUSORDERSERVICE = DESCRIPTOR.services_by_name['CheckStatusOrderService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKSTATUSORDERREQUEST._serialized_start=60
  _CHECKSTATUSORDERREQUEST._serialized_end=99
  _CHECKSTATUSORDERRESPONSE._serialized_start=101
  _CHECKSTATUSORDERRESPONSE._serialized_end=188
  _CHECKSTATUSORDERSERVICE._serialized_start=190
  _CHECKSTATUSORDERSERVICE._serialized_end=300
# @@protoc_insertion_point(module_scope)
